### ISSUE TITLE
关于预训练权重导入的错误

### ISSUE THREAD

**Issue by SoarAnyway** [Jacen789/relation-extraction#6]
但我尝试运行demo_train.py时：

Traceback (most recent call last):
  File "demo_train.py", line 15, in <module>
    main()
  File "demo_train.py", line 11, in main
    train(hparams)
  File "/home/share/kuangwenteng/NRE/relation-extraction/relation_extraction/train.py", line 45, in train
    model = SentenceRE(hparams).to(device)
  File "/home/share/kuangwenteng/NRE/relation-extraction/relation_extraction/model.py", line 21, in __init__
    self.bert_model = BertModel.from_pretrained(self.pretrained_model_path)
  File "/home/ubuntu/anaconda3/envs/nre/lib/python3.6/site-packages/transformers/modeling_utils.py", line 1072, in from_pretrained
    model.__class__.__name__, "\n\t".join(error_msgs)
RuntimeError: Error(s) in loading state_dict for BertModel:
size mismatch for bert.embeddings.word_embeddings.weight: copying a param with shape torch.Size([30522, 768]) from checkpoint, the shape in current model is torch.Size([21128, 768]).

报错与训练权重的size和模型size不一样，该如何解决？

**Comment by Jacen789** [comment]
你是不是修改过BERT的词汇表vocab.txt，还是下载错了与模型语言不对应的其他语言的vocab.txt？请确认一下。

**Comment by SoarAnyway** [comment]
> 你是不是修改过BERT的词汇表vocab.txt，还是下载错了与模型语言不对应的其他语言的vocab.txt？请确认一下。

我用的是你的词汇表vocab.txt，但是下载的模型的词汇表和你的不一样，现在更换过后就ok了

**Comment by Jacen789** [comment]
嗯，你应该用的是“bert-base-uncased”这个预训练模型。
